const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');const run=require('node:util').promisify(require('node:child_process').execFile);
const data=path.resolve(process.env.TAISIAM_DATA_DIR||path.join(__dirname,'../.local-data'));fs.mkdirSync(data,{recursive:true});const runtime=path.join(process.env.USERPROFILE,'.cache/codex-runtimes/codex-primary-runtime/dependencies');const python=path.join(runtime,'python/python.exe'),node=path.join(runtime,'node/bin/node.exe'),storePath=path.join(data,'ledger.json');
const branchAliases={'ในเมือง':'TAI SIAM Tachileik','ริมทาง':'TAI SIAM 2','ตลาดเหนือ':'MOK SIO','บ้านสวน':'TAI SIAM Murng Pan'};
function canonicalBranch(name){return branchAliases[name]||name}
function load(){let db=fs.existsSync(storePath)?JSON.parse(fs.readFileSync(storePath,'utf8')):{revision:0,records:[],history:[]};db.expenses??=[];db.purchases??=[];let changed=false;for(let r of db.records){if(branchAliases[r.branch]){r.branch=canonicalBranch(r.branch);changed=true}}if(changed){db.revision++;db.history.unshift({time:new Date().toISOString(),action:'เปลี่ยนชื่อสาขา',detail:'ใช้ชื่อสาขาจริงตามที่เจ้าของยืนยัน'});save(db)}return db}
function save(db){if(fs.existsSync(storePath))fs.copyFileSync(storePath,storePath+'.bak');fs.writeFileSync(storePath+'.tmp',JSON.stringify(db,null,2));fs.renameSync(storePath+'.tmp',storePath)}
function reply(res,status,x){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(x))}function fail(message,status=400){let e=new Error(message);e.status=status;throw e}
async function body(req,limit=10000000){let n=0,a=[];for await(const p of req){n+=p.length;if(n>limit)fail('ไฟล์ใหญ่เกิน 10 MB',413);a.push(p)}return Buffer.concat(a)}const json=async req=>JSON.parse((await body(req,2000000)).toString());
function validDate(d){return /^\d{4}-\d{2}-\d{2}$/.test(d)&&!isNaN(Date.parse(d))&&new Date(d+'T00:00:00Z').toISOString().slice(0,10)===d&&+d.slice(0,4)>=1900&&+d.slice(0,4)<=2200}
function validRecord(r){if(typeof r.branch!=='string'||!r.branch.trim()||r.branch.length>100)fail('ระบุชื่อสาขาจริง');r.branch=canonicalBranch(r.branch.trim());if(!validDate(r.date||''))fail('วันที่ไม่ถูกต้อง');if(!Array.isArray(r.lines)||!r.lines.length||r.lines.length>100)fail('ต้องมีรายการหัวจ่าย');for(let [idx,l] of r.lines.entries()){l.lineId=String(l.lineId||l.row||idx+1);for(let k of ['liters','price'])if(typeof l[k]!=='number'||!Number.isFinite(l[k])||l[k]<0)fail('ลิตรและราคาต้องเป็นตัวเลขตั้งแต่ศูนย์');for(let k of ['opening','closing','cost','received','discount','credit','debtPaid','legacyR','legacyV','legacyW'])if(l[k]!=null&&(typeof l[k]!=='number'||!Number.isFinite(l[k])||l[k]<0))fail('ค่าตัวเลขไม่ถูกต้อง: '+k);if(!['A','B','C','D'].includes(l.pump))fail('หัวจ่ายไม่ตรงรูปแบบ');if(l.opening!=null&&l.closing!=null&&l.closing<l.opening)fail('มิเตอร์ปิดน้อยกว่าเปิด ต้องตรวจการรีเซ็ตมิเตอร์')}r.sales=Math.round(r.lines.reduce((s,l)=>s+l.liters*l.price,0)*100)/100;r.liters=r.lines.reduce((s,l)=>s+l.liters,0);return r}
function batchPath(id){if(!/^[a-f0-9]{64}$/.test(id||''))fail('รหัสไฟล์ไม่ถูกต้อง');return path.join(data,id+'.json')}function readBatch(id){let p=batchPath(id);if(!fs.existsSync(p))fail('ไม่พบไฟล์',404);let b=JSON.parse(fs.readFileSync(p,'utf8'));for(let g of b.groups)if(g.branch)g.branch=canonicalBranch(g.branch);return b}
async function importBytes(bytes,filename){if(bytes[0]!==80||bytes[1]!==75)fail('กรุณาเลือกไฟล์ .xlsx');let hash=crypto.createHash('sha256').update(bytes).digest('hex'),file=path.join(data,hash+'.xlsx');if(!fs.existsSync(file))fs.writeFileSync(file,bytes);let out;try{out=await run(python,['-X','utf8',path.join(__dirname,'parse_workbook.py'),file],{maxBuffer:8000000,timeout:30000})}catch(e){let msg='อ่าน Excel ไม่สำเร็จ กรุณาตรวจรูปแบบไฟล์';try{msg=JSON.parse(e.stdout).error||msg}catch{}fail(msg)}let b=JSON.parse(out.stdout);Object.assign(b,{id:hash,filename:path.basename(filename||'excel-report.xlsx').slice(0,150),importedAt:new Date().toISOString()});fs.writeFileSync(batchPath(hash),JSON.stringify(b));return b}
async function handle(req,res,url){if(!url.pathname.startsWith('/api/excel'))return false;try{if(req.headers.origin&&req.headers.origin!==`http://${req.headers.host}`||req.headers['sec-fetch-site']==='cross-site')fail('ไม่อนุญาตคำขอข้ามเว็บไซต์',403);let route=url.pathname.slice(10);
if(req.method==='POST'&&route==='/book-entry'){let x=await json(req),db=load();if(x.revision!==db.revision)fail('ข้อมูลเปลี่ยน กรุณาโหลดใหม่',409);let entry=require('./accounting.cjs').validateEntry(x);db[entry.kind].push(entry);db.revision++;db.history.unshift({time:entry.createdAt,action:entry.kind==='expenses'?'บันทึกค่าใช้จ่าย':'บันทึกซื้อน้ำมัน',detail:entry.branch+' / '+entry.date});save(db);reply(res,200,entry);return true}

if(req.method==='GET'&&route==='/state'){let batches=fs.readdirSync(data).filter(f=>/^[a-f0-9]{64}\.json$/.test(f)).map(f=>JSON.parse(fs.readFileSync(path.join(data,f),'utf8'))).map(b=>({id:b.id,filename:b.filename,importedAt:b.importedAt,groups:b.groups.length}));reply(res,200,{...load(),batches});return true}
if(req.method==='POST'&&route==='/import'){reply(res,200,await importBytes(await body(req),decodeURIComponent(req.headers['x-filename']||'excel-report.xlsx')));return true}
if(req.method==='GET'&&route.startsWith('/batch/')){reply(res,200,readBatch(route.split('/')[2]));return true}
if(req.method==='GET'&&route.startsWith('/source/')){let b=readBatch(route.split('/')[2]);res.writeHead(200,{'Content-Type':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','Content-Disposition':"attachment; filename*=UTF-8''"+encodeURIComponent(b.filename),'Cache-Control':'no-store'});res.end(fs.readFileSync(path.join(data,b.id+'.xlsx')));return true}
if(req.method==='POST'&&route==='/commit'){reply(res,200,commitData(await json(req)));return true}
if(req.method==='POST'&&route==='/manual'){let x=await json(req),db=load();if(x.revision!==db.revision)fail('ข้อมูลเปลี่ยนจากอีกหน้าต่าง กรุณาโหลดใหม่',409);let r=validRecord({branch:x.branch,date:x.date,lines:x.lines,note:x.note||'',source:{filename:'กรอกผ่านเว็บ'},status:'รอตรวจ',id:crypto.randomUUID(),createdAt:new Date().toISOString()});for(let l of r.lines){if(l.opening==null||l.closing==null)fail('ต้องกรอกมิเตอร์เปิดและปิด');l.liters=l.closing-l.opening}validRecord(r);if(db.records.some(a=>a.branch===r.branch&&a.date===r.date))fail('วันและสาขานี้มีข้อมูลแล้ว ไม่บันทึกซ้ำ',409);db.records.push(r);db.revision++;db.history.unshift({time:r.createdAt,action:'บันทึกจากเว็บ',detail:r.branch+' / '+r.date});save(db);reply(res,200,r);return true}
if(req.method==='POST'&&route==='/export'){let x=await json(req),db=load(),payload;if(x.batchId){let b=readBatch(x.batchId);payload={mode:'review',records:b.groups.map(g=>({...g,branch:g.branch||x.branch||'TAI SIAM Tachileik',status:'รอตรวจ',source:{filename:b.filename,sheet:b.sheet,row:g.sourceRow},note:g.issues.join(' / ')}))}}else{let records=db.records.filter(r=>(!x.branch||r.branch===x.branch)&&(!x.from||r.date>=x.from)&&(!x.to||r.date<=x.to));payload={mode:'ledger',records,branch:x.branch,from:x.from,to:x.to,expenses:db.expenses.filter(r=>(!x.branch||r.branch===x.branch)&&(!x.from||r.date>=x.from)&&(!x.to||r.date<=x.to)),purchases:db.purchases.filter(r=>(!x.branch||r.branch===x.branch)&&(!x.from||r.date>=x.from)&&(!x.to||r.date<=x.to))}}let id=crypto.randomUUID(),input=path.join(data,id+'.export.json'),out=path.join(data,id+'.xlsx');fs.writeFileSync(input,JSON.stringify(payload));await run(node,[path.join(__dirname,'export_workbook.mjs'),input,out],{maxBuffer:2000000,timeout:120000});res.writeHead(200,{'Content-Type':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','Content-Disposition':`attachment; filename="taisiam-${payload.mode}.xlsx"`,'Cache-Control':'no-store'});res.end(fs.readFileSync(out));fs.unlinkSync(input);fs.unlinkSync(out);return true}
if(req.method==='GET'&&route==='/backup'){res.writeHead(200,{'Content-Type':'application/json','Content-Disposition':'attachment; filename="taisiam-ledger-backup.json"'});res.end(JSON.stringify(load(),null,2));return true}fail('ไม่พบคำขอ',404)
}catch(e){if(!res.headersSent)reply(res,e.status||500,{error:e.status?e.message:'ดำเนินการไม่สำเร็จ ข้อมูลเดิมยังอยู่ กรุณาลองใหม่'});else res.end()}return true}
function semantic(r){return JSON.stringify(r.lines.map(l=>Object.fromEntries(['pump','fuel','opening','closing','liters','cost','price','received','discount','credit','debtPaid','legacyR','legacyV','legacyW'].map(k=>[k,l[k]??null]))))}
function commitData(x){let db=load();if(x.revision!==db.revision)fail('ข้อมูลเปลี่ยนจากอีกหน้าต่าง กรุณาโหลดใหม่',409);let b=readBatch(x.batchId),updates=[],keys=new Set(),ids=new Set();if(!Array.isArray(x.entries)||!x.entries.length)fail('ยังไม่ได้เลือกวัน');for(let e of x.entries){let g=b.groups.find(g=>g.sourceRow===e.sourceRow);if(!g)fail('ไม่พบแถวต้นทาง');if(!e.confirmed||!e.note?.trim())fail('ต้องยืนยันวันที่และระบุหมายเหตุการตรวจ');let r=validRecord({...g,branch:g.branch||x.branch,date:e.date,note:e.note,source:{batchId:b.id,filename:b.filename,sheet:b.sheet,row:g.sourceRow},status:'ตรวจยอดขายแล้ว'});let key=r.branch+'|'+r.date;if(keys.has(key))fail('มีวันที่ซ้ำภายในชุดนำเข้า',409);keys.add(key);let sameSource=db.records.find(a=>a.source.batchId===b.id&&a.source.row===g.sourceRow),old=g.recordId?db.records.find(a=>a.id===g.recordId):sameSource||db.records.find(a=>a.branch===r.branch&&a.date===r.date);if(g.recordId&&!old)fail('รหัสรายการจาก Excel ไม่พบในเว็บนี้ ไม่สร้างซ้ำโดยอัตโนมัติ');if(old){if(ids.has(old.id))fail('รหัสรายการซ้ำในชุดนำเข้า');ids.add(old.id);if(old.branch!==r.branch)fail('ไม่ย้ายสาขาของรายการเดิมจาก Excel');if(e.action!=='update'||e.existingId!==old.id)fail(`วันที่ ${r.date} มีรายการเดิม ต้องเลือกอัปเดตและตรวจผลต่างก่อน`,409);if(db.records.some(a=>a.id!==old.id&&a.branch===r.branch&&a.date===r.date))fail('วันที่ใหม่ชนรายการอื่น',409);r.id=old.id;r.createdAt=old.createdAt;r.updatedAt=new Date().toISOString();r.versions=[...(old.versions||[]),{...old,versions:undefined}]}else{if(e.action==='update')fail('ไม่พบรายการที่เลือกอัปเดต');r.id=crypto.randomUUID();r.createdAt=new Date().toISOString()}updates.push({r,old})}for(let {r,old} of updates){if(old)db.records[db.records.findIndex(a=>a.id===old.id)]=r;else db.records.push(r);db.history.unshift({time:new Date().toISOString(),action:old?'อัปเดตหลังเทียบ Excel':'ยืนยันนำเข้า',detail:`${r.branch} / ${r.date} / ${r.note}`,recordId:r.id})}db.revision++;save(db);return {count:updates.length}}
module.exports={handle,importBytes,load,validRecord,validDate,semantic,commitData};
