import fs from 'node:fs/promises';
import {addAccountingSheets} from './accounting_workbook.mjs';
import {Workbook,SpreadsheetFile} from '@oai/artifact-tool';
const [input,output,previewDir]=process.argv.slice(2);const payload=JSON.parse(await fs.readFile(input,'utf8'));const wb=Workbook.create();
const overview=wb.worksheets.add('ภาพรวม');
const summary=wb.worksheets.add('สรุปยอดขาย'),details=wb.worksheets.add('รายการเว็บ'),source=wb.worksheets.add('ตรวจต้นทาง');
const literal=x=>typeof x==='string'&&/^[=+@]/.test(x)?"'"+x:x??null;
const dateValue=d=>d&&/^\d{4}-\d{2}-\d{2}$/.test(d)?new Date(d+'T00:00:00Z'):null;
summary.getRange('A2').values=[['ไตยสยาม — สรุปยอดขาย']];summary.getRange('A3').values=[['ยอดขายก่อนส่วนลด/ขายเชื่อ ไม่ใช่เงินรับหรือกำไร • ยอดวัดจริง/เกิน/หายเป็นลิตร']];
details.getRange('A1').values=[['TAISIAM_LEDGER_V1']];details.getRange('A2').values=[['แก้ช่องกรอกแล้วนำกลับเข้าเว็บเพื่อตรวจค่าเดิม–ค่าใหม่ รักษารหัสรายการและรหัสแถวเดิม']];
const headers=['วันที่','สาขา','รหัสรายการ','รหัสแถว','ชนิดแถว','หัวจ่าย','ชนิดน้ำมัน','มิเตอร์เปิด','มิเตอร์ปิด','ลิตรจัดสรร (ถ้ามี)','ลิตรขาย','ต้นทุน/ลิตร','ราคาขาย/ลิตร','ยอดขายก่อนปรับ','ส่วนลด (บาท)','ขายเชื่อ (บาท)','รับชำระหนี้ (บาท)','รับเข้า (ลิตร)','วัดจริง (ลิตร)','เกิน (ลิตร)','หาย (ลิตร)','สถานะ','ต้นทาง','หมายเหตุ'];
details.getRange('A4:X4').values=[headers];summary.getRange('A5:K5').values=[['วันที่','สาขา','ลิตรขาย','ยอดขายก่อนปรับ','ส่วนลด (บาท)','ขายเชื่อ (บาท)','รับชำระหนี้','รับเข้า (ลิตร)','สถานะ','วันที่ในต้นฉบับ','หมายเหตุ']];source.getRange('A2').values=[['ข้อมูลและสูตรจากต้นทางสำหรับตรวจสอบ']];source.getRange('A4:F4').values=[['ไฟล์ต้นทาง','ชีต','เซลล์','ค่าหรือสูตรเดิม (ข้อความ)','ค่าที่ Excel บันทึกล่าสุด','วันที่ที่ตรวจ']];
let dr=5,sr=6,rr=5;for(const record of payload.records){let start=dr;for(const [index,l] of record.lines.entries()){
let override=l.split||l.opening==null||l.closing==null||Math.abs(l.closing-l.opening-l.liters)>.00001?l.liters:null;
let row=[dateValue(record.date),record.branch,record.id||record.recordId||('review:'+record.sourceRow),l.lineId||String(l.row||index+1),l.split?'แยกต้นทุน':'หัวจ่าย',l.pump,l.fuel,l.opening,l.closing,override,null,l.cost,l.price,null,l.discount,l.credit,l.debtPaid,l.received,l.legacyR,l.legacyV,l.legacyW,record.status||'รอตรวจ',`${record.source?.filename||''} / ${record.source?.sheet||''} / ${l.row||''}`,record.note||''];details.getRange(`A${dr}:X${dr}`).values=[row.map(literal)];details.getRange(`K${dr}`).formulas=[[`=IF(J${dr}="",IF(OR(H${dr}="",I${dr}=""),"",I${dr}-H${dr}),J${dr})`]];details.getRange(`N${dr}`).formulas=[[`=IF(OR(K${dr}="",M${dr}=""),"",K${dr}*M${dr})`]];
for(const [col,raw] of Object.entries(l.raw||{})){source.getRange(`A${rr}:F${rr}`).values=[[record.source?.filename||'',record.source?.sheet||'',col+(l.row||''),literal(raw.value),literal(raw.cached),dateValue(record.date)]];rr++}dr++}
summary.getRange(`A${sr}:K${sr}`).values=[[dateValue(record.date),literal(record.branch),null,null,null,null,null,null,record.status||'รอตรวจ',record.rawDate||record.date||'',literal(record.note||'')]];for(const [to,from] of [['C','K'],['D','N'],['E','O'],['F','P'],['G','Q'],['H','R']])summary.getRange(`${to}${sr}`).formulas=[[`=SUM('รายการเว็บ'!${from}${start}:${from}${dr-1})`]];sr++}
dr=Math.max(dr,6);sr=Math.max(sr,7);rr=Math.max(rr,6);
summary.getRange(`B${sr}`).values=[['รวม']];for(const col of ['C','D','E','F','G','H'])summary.getRange(`${col}${sr}`).formulas=[[`=SUM(${col}6:${col}${sr-1})`]];
for(const [s,last,end,header] of [[summary,sr,'K',5],[details,dr-1,'X',4],[source,Math.max(rr-1,4),'F',4]]){s.showGridLines=false;s.getRange(`A1:${end}${last}`).format.font={name:'Arial',size:11,color:'#21354F'};s.getRange(`A${header}:${end}${header}`).format={fill:'#244A81',font:{bold:true,color:'#FFFFFF'},wrapText:true,rowHeight:36};s.getRange(`A${header+1}:${end}${last}`).format.rowHeight=25;s.getRange(`A1:${end}${last}`).format.columnWidth=18;s.getRange('A2').format.font={name:'Arial',size:15,bold:true};s.freezePanes.freezeRows(header)}
summary.getRange(`A6:A${sr-1}`).setNumberFormat('dd/mm/yyyy');details.getRange(`A5:A${dr-1}`).setNumberFormat('dd/mm/yyyy');source.getRange(`F5:F${Math.max(5,rr-1)}`).setNumberFormat('dd/mm/yyyy');summary.getRange(`C6:H${sr}`).setNumberFormat('#,##0.00');details.getRange(`H5:U${dr-1}`).setNumberFormat('#,##0.00');summary.getRange(`B${sr}:K${sr}`).format.font.bold=true;
summary.getRange(`B1:B${sr}`).format.columnWidth=32;summary.getRange(`J1:J${sr}`).format.columnWidth=25;summary.getRange(`K1:K${sr}`).format.columnWidth=65;summary.getRange(`K6:K${sr-1}`).format.wrapText=true;summary.getRange(`A6:K${sr-1}`).format.autofitRows();
details.getRange(`C1:D${dr-1}`).format.columnWidth=38;details.getRange(`W1:W${dr-1}`).format.columnWidth=45;details.getRange(`X1:X${dr-1}`).format.columnWidth=60;details.getRange(`X5:X${dr-1}`).format.wrapText=true;details.getRange(`A5:X${dr-1}`).format.autofitRows();details.getRange(`H5:J${dr-1}`).format.font.color='#245BCD';details.getRange(`L5:M${dr-1}`).format.font.color='#245BCD';details.getRange(`O5:U${dr-1}`).format.font.color='#245BCD';details.getRange(`K5:K${dr-1}`).format.fill='#EEF2F7';details.getRange(`N5:N${dr-1}`).format.fill='#EEF2F7';
source.getRange(`A1:A${Math.max(rr-1,5)}`).format.columnWidth=28;source.getRange(`D1:D${Math.max(rr-1,5)}`).format.columnWidth=65;source.getRange(`E1:E${Math.max(rr-1,5)}`).format.columnWidth=26;source.getRange(`D5:D${Math.max(5,rr-1)}`).format.wrapText=true;source.getRange(`A5:F${Math.max(5,rr-1)}`).format.autofitRows();
addAccountingSheets(wb,payload,overview,dr-1,sr);
wb.recalculate();
if(previewDir){await fs.mkdir(previewDir,{recursive:true});for(const [s,r] of [['สรุปยอดขาย','A1:I10'],['รายการเว็บ','E4:Q10'],['ตรวจต้นทาง','A1:F12'],['ภาพรวม','A1:B19'],['ค่าใช้จ่ายรายวัน','A1:F8'],['ซื้อน้ำมันเข้า','A1:I9'],['ยอดขายรายเดือน','A1:J9'],['เงินรับจ่ายรายเดือน','A1:I9']]){const image=await wb.render({sheetName:s,range:r,scale:1.5,format:'png'});await fs.writeFile(`${previewDir}/${s}.png`,new Uint8Array(await image.arrayBuffer()))}console.log((await wb.inspect({kind:'table',range:`'สรุปยอดขาย'!B${sr}:H${sr}`,include:'values,formulas',maxChars:1200,tableMaxRows:2,tableMaxCols:7})).ndjson);console.log((await wb.inspect({kind:'match',searchTerm:'#REF!|#DIV/0!|#VALUE!|#NAME\\?|#NUM!',options:{useRegex:true,maxResults:10},maxChars:1000})).ndjson)}
await(await SpreadsheetFile.exportXlsx(wb)).save(output);console.log(JSON.stringify({rows:dr-5,days:payload.records.length,output}));
