import crypto from 'node:crypto';
export function fail(message,status=400){throw Object.assign(new Error(message),{status})}
const branchAliases={'ในเมือง':'TAI SIAM Tachileik','ริมทาง':'TAI SIAM 2','ตลาดเหนือ':'MOK SIO','บ้านสวน':'TAI SIAM Murng Pan'};
function canonicalBranch(name){return branchAliases[name]||name}
function validDate(d){return /^\d{4}-\d{2}-\d{2}$/.test(d)&&!isNaN(Date.parse(d))&&new Date(d+'T00:00:00Z').toISOString().slice(0,10)===d&&+d.slice(0,4)>=1900&&+d.slice(0,4)<=2200}
function validRecord(r){if(typeof r.branch!=='string'||!r.branch.trim()||r.branch.length>100)fail('ระบุชื่อสาขาจริง');r.branch=canonicalBranch(r.branch.trim());if(!validDate(r.date||''))fail('วันที่ไม่ถูกต้อง');if(!Array.isArray(r.lines)||!r.lines.length||r.lines.length>100)fail('ต้องมีรายการหัวจ่าย');for(let [idx,l] of r.lines.entries()){l.lineId=String(l.lineId||l.row||idx+1);for(let k of ['liters','price'])if(typeof l[k]!=='number'||!Number.isFinite(l[k])||l[k]<0)fail('ลิตรและราคาต้องเป็นตัวเลขตั้งแต่ศูนย์');for(let k of ['opening','closing','cost','received','discount','credit','debtPaid','legacyR','legacyV','legacyW'])if(l[k]!=null&&(typeof l[k]!=='number'||!Number.isFinite(l[k])||l[k]<0))fail('ค่าตัวเลขไม่ถูกต้อง: '+k);if(!['A','B','C','D'].includes(l.pump))fail('หัวจ่ายไม่ตรงรูปแบบ');if(l.opening!=null&&l.closing!=null&&l.closing<l.opening)fail('มิเตอร์ปิดน้อยกว่าเปิด ต้องตรวจการรีเซ็ตมิเตอร์')}r.sales=Math.round(r.lines.reduce((s,l)=>s+l.liters*l.price,0)*100)/100;r.liters=r.lines.reduce((s,l)=>s+l.liters,0);return r}
function commitData(x,db,b){if(x.revision!==db.revision)fail('ข้อมูลเปลี่ยนจากอีกหน้าต่าง กรุณาโหลดใหม่',409);let updates=[],keys=new Set(),ids=new Set();if(!Array.isArray(x.entries)||!x.entries.length)fail('ยังไม่ได้เลือกวัน');for(let e of x.entries){let g=b.groups.find(g=>g.sourceRow===e.sourceRow);if(!g)fail('ไม่พบแถวต้นทาง');if(!e.confirmed||!e.note?.trim())fail('ต้องยืนยันวันที่และระบุหมายเหตุการตรวจ');let r=validRecord({...g,branch:g.branch||x.branch,date:e.date,note:e.note,source:{batchId:b.id,filename:b.filename,sheet:b.sheet,row:g.sourceRow},status:'ตรวจยอดขายแล้ว'});let key=r.branch+'|'+r.date;if(keys.has(key))fail('มีวันที่ซ้ำภายในชุดนำเข้า',409);keys.add(key);let sameSource=db.records.find(a=>a.source.batchId===b.id&&a.source.row===g.sourceRow),old=g.recordId?db.records.find(a=>a.id===g.recordId):sameSource||db.records.find(a=>a.branch===r.branch&&a.date===r.date);if(g.recordId&&!old)fail('รหัสรายการจาก Excel ไม่พบในเว็บนี้ ไม่สร้างซ้ำโดยอัตโนมัติ');if(old){if(ids.has(old.id))fail('รหัสรายการซ้ำในชุดนำเข้า');ids.add(old.id);if(old.branch!==r.branch)fail('ไม่ย้ายสาขาของรายการเดิมจาก Excel');if(e.action!=='update'||e.existingId!==old.id)fail(`วันที่ ${r.date} มีรายการเดิม ต้องเลือกอัปเดตและตรวจผลต่างก่อน`,409);if(db.records.some(a=>a.id!==old.id&&a.branch===r.branch&&a.date===r.date))fail('วันที่ใหม่ชนรายการอื่น',409);r.id=old.id;r.createdAt=old.createdAt;r.updatedAt=new Date().toISOString();r.versions=[...(old.versions||[]),{...old,versions:undefined}]}else{if(e.action==='update')fail('ไม่พบรายการที่เลือกอัปเดต');r.id=crypto.randomUUID();r.createdAt=new Date().toISOString()}updates.push({r,old})}for(let {r,old} of updates){if(old)db.records[db.records.findIndex(a=>a.id===old.id)]=r;else db.records.push(r);db.history.unshift({time:new Date().toISOString(),action:old?'อัปเดตหลังเทียบ Excel':'ยืนยันนำเข้า',detail:`${r.branch} / ${r.date} / ${r.note}`,recordId:r.id})}db.revision++;return {count:updates.length}}

export {validDate,validRecord,commitData};
